### ISSUE TITLE
Got ahead of myself as reader expecting that clicking the button would toggle

### ISSUE THREAD

**Issue by brigj1** [learn-co-curriculum/react-hooks-state-and-events-codealong#2]
### Canvas Link

https://learning.flatironschool.com/courses/5186/assignments/180108?module_item_id=397494

### Concern

In this phrase:
You should now be able to change the initial state in the useState function

it didn't register with me as a reader that it was suggesting experimenting with "false" and "true" by updating those hardcoded terms manually. My mind was set to expect clicking the button to change the value, so it seemed like a misplaced paragraph to read that I could already change the state. With no automation?

After much careful re-reading, I see the word "initial". Ohhhh. Struggle is good, but not as regards to reading/learning this concept. Maybe a little heads-up about "manually" wouldn't hurt.

### Suggested Changes

Perhaps simply make "initial" in this phrase in italics:
You should now be able to change the initial state in the useState function

That would provide a little more hint to not get ahead of ourselves.
Or could be more explicit:

You should now be able to change the initial state manually in the useState function

**Comment by professor-ben** [comment]
Hi Brigham,

I think that this formatting is consistent with how we write the instructions in other repos, so in this particular case I believe it would be best to leave the text as-is.

Thank you for your diligence,
Ben

**Comment by brigj1** [comment]
Hi Ben,
Sample size of one here. :-)

For me, in retrospect, I would have appreciated something that reached out
from the page and poked me to say that the word "initial" there is
super-important. Don't speed-read through it, else one misses the point and
must re-read to catch it. (Or doesn't notice there is a point and goes on
having missed the point.) It's fine as an author to intend that readers
will catch the meaning; I'm sharing my experience as a reader that I missed
the connection.

I don't know about formatting of other repos. However, in this very page,
there are several examples of italicizing terms to emphasize their
importance, e.g.

Any time we want to *update* state, we need to use the *setter function*
 returned

For me, I think emphasizing (italicizing) "initial" would have helped me
clue in faster. My time and attention for reading the firehose of course
material is limited, so the more the course can do to make it go down nice
and easy (as is the case overall - yay!) the better my learning experience
will be.
(My time and attention for picking at grammar is inexhaustible! :-) But
from intent to help improve.)

Thanks,
Brigham Johnson
