### ISSUE TITLE
Typo/grammar in Code Challenge wording

### ISSUE THREAD

**Issue by brigj1** [learn-co-curriculum/react-hooks-state-and-events-codealong#3]
### Canvas Link

https://learning.flatironschool.com/courses/5186/assignments/180093

### Concern

grammar issues in the following:
Your job will be to make our app work according to the user stories you will find the Core Deliverables section.

Code Challenges are stressful. It adds unnecessary stress when taking a quiz to encounter incorrect grammar, however obvious its intent might be.

### Suggested Changes

Instead of this:
Your job will be to make our app work according to the user stories you will find the Core Deliverables section.

Maybe this?:
Your job will be to make our app work according to the user stories you will find in the Core Deliverables section.

**Comment by professor-ben** [comment]
Hi Brigham,

This is now fixed in the gregslist repo. Please make sure to double check that you are submitting tickets in the same repo where we can find the code or text that needs to be fixed.

Thanks,
Ben

**Comment by brigj1** [comment]
Oops, sorry. Sounds like the fix happened in a different page than the one
I would have referenced. I try to gather the link directly from the
affected page, I'll look out for that. Thanks!
